package:
  name: traffic_analysis
  version: 1.2.310174

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

# test:
#   imports:
#     - traffic_analysis

about:
  home: https://github.com/sohaibahmad759/mlserving_pipelined
  license: 
  license_file: 
