# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import worker_pb2 as protos_dot_worker__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/client.proto',
  package='pipescaler',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13protos/client.proto\x12\npipescaler\x1a\x13protos/worker.proto\"\x86\x01\n\x11InferenceResponse\x12\x0e\n\x06userID\x18\x01 \x01(\t\x12\x15\n\rapplicationID\x18\x02 \x01(\t\x12\x11\n\trequestID\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x0c\x12)\n\x06status\x18\x05 \x01(\x0e\x32\x19.pipescaler.RequestStatus\"r\n\x14InferenceResponseAck\x12\x0e\n\x06userID\x18\x01 \x01(\t\x12\x15\n\rapplicationID\x18\x02 \x01(\t\x12\x11\n\trequestID\x18\x03 \x01(\t\x12\x14\n\x07message\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2\xb4\x01\n\x06\x43lient\x12R\n\rFinishRequest\x12\x1d.pipescaler.InferenceResponse\x1a .pipescaler.InferenceResponseAck\"\x00\x12V\n\x0fSetRoutingTable\x12\x1f.pipescaler.RoutingTableRequest\x1a .pipescaler.RoutingTableResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[protos_dot_worker__pb2.DESCRIPTOR,])




_INFERENCERESPONSE = _descriptor.Descriptor(
  name='InferenceResponse',
  full_name='pipescaler.InferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='pipescaler.InferenceResponse.userID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='applicationID', full_name='pipescaler.InferenceResponse.applicationID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestID', full_name='pipescaler.InferenceResponse.requestID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='pipescaler.InferenceResponse.data', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='pipescaler.InferenceResponse.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=191,
)


_INFERENCERESPONSEACK = _descriptor.Descriptor(
  name='InferenceResponseAck',
  full_name='pipescaler.InferenceResponseAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='pipescaler.InferenceResponseAck.userID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='applicationID', full_name='pipescaler.InferenceResponseAck.applicationID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestID', full_name='pipescaler.InferenceResponseAck.requestID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='pipescaler.InferenceResponseAck.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_message', full_name='pipescaler.InferenceResponseAck._message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=193,
  serialized_end=307,
)

_INFERENCERESPONSE.fields_by_name['status'].enum_type = protos_dot_worker__pb2._REQUESTSTATUS
_INFERENCERESPONSEACK.oneofs_by_name['_message'].fields.append(
  _INFERENCERESPONSEACK.fields_by_name['message'])
_INFERENCERESPONSEACK.fields_by_name['message'].containing_oneof = _INFERENCERESPONSEACK.oneofs_by_name['_message']
DESCRIPTOR.message_types_by_name['InferenceResponse'] = _INFERENCERESPONSE
DESCRIPTOR.message_types_by_name['InferenceResponseAck'] = _INFERENCERESPONSEACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferenceResponse = _reflection.GeneratedProtocolMessageType('InferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCERESPONSE,
  '__module__' : 'protos.client_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.InferenceResponse)
  })
_sym_db.RegisterMessage(InferenceResponse)

InferenceResponseAck = _reflection.GeneratedProtocolMessageType('InferenceResponseAck', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCERESPONSEACK,
  '__module__' : 'protos.client_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.InferenceResponseAck)
  })
_sym_db.RegisterMessage(InferenceResponseAck)



_CLIENT = _descriptor.ServiceDescriptor(
  name='Client',
  full_name='pipescaler.Client',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=310,
  serialized_end=490,
  methods=[
  _descriptor.MethodDescriptor(
    name='FinishRequest',
    full_name='pipescaler.Client.FinishRequest',
    index=0,
    containing_service=None,
    input_type=_INFERENCERESPONSE,
    output_type=_INFERENCERESPONSEACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetRoutingTable',
    full_name='pipescaler.Client.SetRoutingTable',
    index=1,
    containing_service=None,
    input_type=protos_dot_worker__pb2._ROUTINGTABLEREQUEST,
    output_type=protos_dot_worker__pb2._ROUTINGTABLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENT)

DESCRIPTOR.services_by_name['Client'] = _CLIENT

# @@protoc_insertion_point(module_scope)
