# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import controller_pb2 as protos_dot_controller__pb2


class ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WorkerSetup = channel.unary_unary(
                '/pipescaler.Controller/WorkerSetup',
                request_serializer=protos_dot_controller__pb2.RegisterWorker.SerializeToString,
                response_deserializer=protos_dot_controller__pb2.RegisterWorkerResponse.FromString,
                )
        self.LBSetup = channel.unary_unary(
                '/pipescaler.Controller/LBSetup',
                request_serializer=protos_dot_controller__pb2.RegisterLB.SerializeToString,
                response_deserializer=protos_dot_controller__pb2.RegisterLBResponse.FromString,
                )


class ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WorkerSetup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LBSetup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WorkerSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerSetup,
                    request_deserializer=protos_dot_controller__pb2.RegisterWorker.FromString,
                    response_serializer=protos_dot_controller__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'LBSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.LBSetup,
                    request_deserializer=protos_dot_controller__pb2.RegisterLB.FromString,
                    response_serializer=protos_dot_controller__pb2.RegisterLBResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipescaler.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WorkerSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pipescaler.Controller/WorkerSetup',
            protos_dot_controller__pb2.RegisterWorker.SerializeToString,
            protos_dot_controller__pb2.RegisterWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LBSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pipescaler.Controller/LBSetup',
            protos_dot_controller__pb2.RegisterLB.SerializeToString,
            protos_dot_controller__pb2.RegisterLBResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
