# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/controller.proto',
  package='pipescaler',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17protos/controller.proto\x12\npipescaler\"B\n\x0eRegisterWorker\x12\x0e\n\x06hostID\x18\x01 \x01(\t\x12\x0e\n\x06hostIP\x18\x02 \x01(\t\x12\x10\n\x08hostPort\x18\x03 \x01(\t\"X\n\x16RegisterWorkerResponse\x12\x0c\n\x04lbIP\x18\x01 \x01(\t\x12\x0e\n\x06lbPort\x18\x02 \x01(\t\x12\x14\n\x07message\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"*\n\nRegisterLB\x12\x0c\n\x04lbIP\x18\x01 \x01(\t\x12\x0e\n\x06lbPort\x18\x02 \x01(\t\"%\n\x12RegisterLBResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa2\x01\n\nController\x12O\n\x0bWorkerSetup\x12\x1a.pipescaler.RegisterWorker\x1a\".pipescaler.RegisterWorkerResponse\"\x00\x12\x43\n\x07LBSetup\x12\x16.pipescaler.RegisterLB\x1a\x1e.pipescaler.RegisterLBResponse\"\x00\x62\x06proto3'
)




_REGISTERWORKER = _descriptor.Descriptor(
  name='RegisterWorker',
  full_name='pipescaler.RegisterWorker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostID', full_name='pipescaler.RegisterWorker.hostID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hostIP', full_name='pipescaler.RegisterWorker.hostIP', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hostPort', full_name='pipescaler.RegisterWorker.hostPort', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=105,
)


_REGISTERWORKERRESPONSE = _descriptor.Descriptor(
  name='RegisterWorkerResponse',
  full_name='pipescaler.RegisterWorkerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lbIP', full_name='pipescaler.RegisterWorkerResponse.lbIP', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lbPort', full_name='pipescaler.RegisterWorkerResponse.lbPort', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='pipescaler.RegisterWorkerResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_message', full_name='pipescaler.RegisterWorkerResponse._message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=107,
  serialized_end=195,
)


_REGISTERLB = _descriptor.Descriptor(
  name='RegisterLB',
  full_name='pipescaler.RegisterLB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lbIP', full_name='pipescaler.RegisterLB.lbIP', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lbPort', full_name='pipescaler.RegisterLB.lbPort', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=239,
)


_REGISTERLBRESPONSE = _descriptor.Descriptor(
  name='RegisterLBResponse',
  full_name='pipescaler.RegisterLBResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pipescaler.RegisterLBResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=278,
)

_REGISTERWORKERRESPONSE.oneofs_by_name['_message'].fields.append(
  _REGISTERWORKERRESPONSE.fields_by_name['message'])
_REGISTERWORKERRESPONSE.fields_by_name['message'].containing_oneof = _REGISTERWORKERRESPONSE.oneofs_by_name['_message']
DESCRIPTOR.message_types_by_name['RegisterWorker'] = _REGISTERWORKER
DESCRIPTOR.message_types_by_name['RegisterWorkerResponse'] = _REGISTERWORKERRESPONSE
DESCRIPTOR.message_types_by_name['RegisterLB'] = _REGISTERLB
DESCRIPTOR.message_types_by_name['RegisterLBResponse'] = _REGISTERLBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterWorker = _reflection.GeneratedProtocolMessageType('RegisterWorker', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERWORKER,
  '__module__' : 'protos.controller_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.RegisterWorker)
  })
_sym_db.RegisterMessage(RegisterWorker)

RegisterWorkerResponse = _reflection.GeneratedProtocolMessageType('RegisterWorkerResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERWORKERRESPONSE,
  '__module__' : 'protos.controller_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.RegisterWorkerResponse)
  })
_sym_db.RegisterMessage(RegisterWorkerResponse)

RegisterLB = _reflection.GeneratedProtocolMessageType('RegisterLB', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERLB,
  '__module__' : 'protos.controller_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.RegisterLB)
  })
_sym_db.RegisterMessage(RegisterLB)

RegisterLBResponse = _reflection.GeneratedProtocolMessageType('RegisterLBResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERLBRESPONSE,
  '__module__' : 'protos.controller_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.RegisterLBResponse)
  })
_sym_db.RegisterMessage(RegisterLBResponse)



_CONTROLLER = _descriptor.ServiceDescriptor(
  name='Controller',
  full_name='pipescaler.Controller',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=443,
  methods=[
  _descriptor.MethodDescriptor(
    name='WorkerSetup',
    full_name='pipescaler.Controller.WorkerSetup',
    index=0,
    containing_service=None,
    input_type=_REGISTERWORKER,
    output_type=_REGISTERWORKERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LBSetup',
    full_name='pipescaler.Controller.LBSetup',
    index=1,
    containing_service=None,
    input_type=_REGISTERLB,
    output_type=_REGISTERLBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLLER)

DESCRIPTOR.services_by_name['Controller'] = _CONTROLLER

# @@protoc_insertion_point(module_scope)
