# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import load_balancer_pb2 as protos_dot_load__balancer__pb2


class LoadBalancerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LBAlive = channel.unary_unary(
                '/pipescaler.LoadBalancer/LBAlive',
                request_serializer=protos_dot_load__balancer__pb2.LBHeartbeat.SerializeToString,
                response_deserializer=protos_dot_load__balancer__pb2.LBHeartbeatResponse.FromString,
                )
        self.WorkerSetup = channel.unary_unary(
                '/pipescaler.LoadBalancer/WorkerSetup',
                request_serializer=protos_dot_load__balancer__pb2.RegisterWorkerAtLB.SerializeToString,
                response_deserializer=protos_dot_load__balancer__pb2.RegisterWorkerAtLBResponse.FromString,
                )
        self.ClientSetup = channel.unary_unary(
                '/pipescaler.LoadBalancer/ClientSetup',
                request_serializer=protos_dot_load__balancer__pb2.RegisterClient.SerializeToString,
                response_deserializer=protos_dot_load__balancer__pb2.RegisterClientResponse.FromString,
                )


class LoadBalancerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LBAlive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkerSetup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientSetup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoadBalancerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LBAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.LBAlive,
                    request_deserializer=protos_dot_load__balancer__pb2.LBHeartbeat.FromString,
                    response_serializer=protos_dot_load__balancer__pb2.LBHeartbeatResponse.SerializeToString,
            ),
            'WorkerSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerSetup,
                    request_deserializer=protos_dot_load__balancer__pb2.RegisterWorkerAtLB.FromString,
                    response_serializer=protos_dot_load__balancer__pb2.RegisterWorkerAtLBResponse.SerializeToString,
            ),
            'ClientSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientSetup,
                    request_deserializer=protos_dot_load__balancer__pb2.RegisterClient.FromString,
                    response_serializer=protos_dot_load__balancer__pb2.RegisterClientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipescaler.LoadBalancer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LoadBalancer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LBAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pipescaler.LoadBalancer/LBAlive',
            protos_dot_load__balancer__pb2.LBHeartbeat.SerializeToString,
            protos_dot_load__balancer__pb2.LBHeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WorkerSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pipescaler.LoadBalancer/WorkerSetup',
            protos_dot_load__balancer__pb2.RegisterWorkerAtLB.SerializeToString,
            protos_dot_load__balancer__pb2.RegisterWorkerAtLBResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pipescaler.LoadBalancer/ClientSetup',
            protos_dot_load__balancer__pb2.RegisterClient.SerializeToString,
            protos_dot_load__balancer__pb2.RegisterClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
