# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/load_balancer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/load_balancer.proto',
  package='pipescaler',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aprotos/load_balancer.proto\x12\npipescaler\"\x1e\n\x0bLBHeartbeat\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x13LBHeartbeatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"t\n\x12RegisterWorkerAtLB\x12\x0e\n\x06hostID\x18\x01 \x01(\t\x12\x0e\n\x06hostIP\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\r\n\x05\x61ppID\x18\x04 \x01(\t\x12\x0c\n\x04task\x18\x05 \x01(\t\x12\x13\n\x0bloadedModel\x18\x06 \x01(\t\"-\n\x1aRegisterWorkerAtLBResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"M\n\x0eRegisterClient\x12\x0e\n\x06hostID\x18\x01 \x01(\t\x12\x0e\n\x06hostIP\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\r\n\x05\x61ppID\x18\x04 \x01(\t\")\n\x16RegisterClientResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xff\x01\n\x0cLoadBalancer\x12\x45\n\x07LBAlive\x12\x17.pipescaler.LBHeartbeat\x1a\x1f.pipescaler.LBHeartbeatResponse\"\x00\x12W\n\x0bWorkerSetup\x12\x1e.pipescaler.RegisterWorkerAtLB\x1a&.pipescaler.RegisterWorkerAtLBResponse\"\x00\x12O\n\x0b\x43lientSetup\x12\x1a.pipescaler.RegisterClient\x1a\".pipescaler.RegisterClientResponse\"\x00\x62\x06proto3'
)




_LBHEARTBEAT = _descriptor.Descriptor(
  name='LBHeartbeat',
  full_name='pipescaler.LBHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pipescaler.LBHeartbeat.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=72,
)


_LBHEARTBEATRESPONSE = _descriptor.Descriptor(
  name='LBHeartbeatResponse',
  full_name='pipescaler.LBHeartbeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pipescaler.LBHeartbeatResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=112,
)


_REGISTERWORKERATLB = _descriptor.Descriptor(
  name='RegisterWorkerAtLB',
  full_name='pipescaler.RegisterWorkerAtLB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostID', full_name='pipescaler.RegisterWorkerAtLB.hostID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hostIP', full_name='pipescaler.RegisterWorkerAtLB.hostIP', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='pipescaler.RegisterWorkerAtLB.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appID', full_name='pipescaler.RegisterWorkerAtLB.appID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task', full_name='pipescaler.RegisterWorkerAtLB.task', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loadedModel', full_name='pipescaler.RegisterWorkerAtLB.loadedModel', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=230,
)


_REGISTERWORKERATLBRESPONSE = _descriptor.Descriptor(
  name='RegisterWorkerAtLBResponse',
  full_name='pipescaler.RegisterWorkerAtLBResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pipescaler.RegisterWorkerAtLBResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=277,
)


_REGISTERCLIENT = _descriptor.Descriptor(
  name='RegisterClient',
  full_name='pipescaler.RegisterClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostID', full_name='pipescaler.RegisterClient.hostID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hostIP', full_name='pipescaler.RegisterClient.hostIP', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='pipescaler.RegisterClient.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appID', full_name='pipescaler.RegisterClient.appID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=356,
)


_REGISTERCLIENTRESPONSE = _descriptor.Descriptor(
  name='RegisterClientResponse',
  full_name='pipescaler.RegisterClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pipescaler.RegisterClientResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=399,
)

DESCRIPTOR.message_types_by_name['LBHeartbeat'] = _LBHEARTBEAT
DESCRIPTOR.message_types_by_name['LBHeartbeatResponse'] = _LBHEARTBEATRESPONSE
DESCRIPTOR.message_types_by_name['RegisterWorkerAtLB'] = _REGISTERWORKERATLB
DESCRIPTOR.message_types_by_name['RegisterWorkerAtLBResponse'] = _REGISTERWORKERATLBRESPONSE
DESCRIPTOR.message_types_by_name['RegisterClient'] = _REGISTERCLIENT
DESCRIPTOR.message_types_by_name['RegisterClientResponse'] = _REGISTERCLIENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LBHeartbeat = _reflection.GeneratedProtocolMessageType('LBHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _LBHEARTBEAT,
  '__module__' : 'protos.load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.LBHeartbeat)
  })
_sym_db.RegisterMessage(LBHeartbeat)

LBHeartbeatResponse = _reflection.GeneratedProtocolMessageType('LBHeartbeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _LBHEARTBEATRESPONSE,
  '__module__' : 'protos.load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.LBHeartbeatResponse)
  })
_sym_db.RegisterMessage(LBHeartbeatResponse)

RegisterWorkerAtLB = _reflection.GeneratedProtocolMessageType('RegisterWorkerAtLB', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERWORKERATLB,
  '__module__' : 'protos.load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.RegisterWorkerAtLB)
  })
_sym_db.RegisterMessage(RegisterWorkerAtLB)

RegisterWorkerAtLBResponse = _reflection.GeneratedProtocolMessageType('RegisterWorkerAtLBResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERWORKERATLBRESPONSE,
  '__module__' : 'protos.load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.RegisterWorkerAtLBResponse)
  })
_sym_db.RegisterMessage(RegisterWorkerAtLBResponse)

RegisterClient = _reflection.GeneratedProtocolMessageType('RegisterClient', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCLIENT,
  '__module__' : 'protos.load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.RegisterClient)
  })
_sym_db.RegisterMessage(RegisterClient)

RegisterClientResponse = _reflection.GeneratedProtocolMessageType('RegisterClientResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCLIENTRESPONSE,
  '__module__' : 'protos.load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:pipescaler.RegisterClientResponse)
  })
_sym_db.RegisterMessage(RegisterClientResponse)



_LOADBALANCER = _descriptor.ServiceDescriptor(
  name='LoadBalancer',
  full_name='pipescaler.LoadBalancer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=402,
  serialized_end=657,
  methods=[
  _descriptor.MethodDescriptor(
    name='LBAlive',
    full_name='pipescaler.LoadBalancer.LBAlive',
    index=0,
    containing_service=None,
    input_type=_LBHEARTBEAT,
    output_type=_LBHEARTBEATRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WorkerSetup',
    full_name='pipescaler.LoadBalancer.WorkerSetup',
    index=1,
    containing_service=None,
    input_type=_REGISTERWORKERATLB,
    output_type=_REGISTERWORKERATLBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ClientSetup',
    full_name='pipescaler.LoadBalancer.ClientSetup',
    index=2,
    containing_service=None,
    input_type=_REGISTERCLIENT,
    output_type=_REGISTERCLIENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADBALANCER)

DESCRIPTOR.services_by_name['LoadBalancer'] = _LOADBALANCER

# @@protoc_insertion_point(module_scope)
